# Generated by Django 4.0.4 on 2022-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_options_remove_product_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=90, verbose_name='Регион'),
        ),
    ]
